"""empty message

Revision ID: 1bd10316c5ab
Revises: 70b8fd78568f
Create Date: 2023-03-17 06:21:29.070037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd10316c5ab'
down_revision = '70b8fd78568f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_stock_symbol_fkey', type_='foreignkey')

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_constraint('position_stock_symbol_fkey', type_='foreignkey')

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_constraint('trade_stock_symbol_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_foreign_key('trade_stock_symbol_fkey', 'stock', ['stock_symbol'], ['symbol'])

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.create_foreign_key('position_stock_symbol_fkey', 'stock', ['stock_symbol'], ['symbol'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_foreign_key('order_stock_symbol_fkey', 'stock', ['stock_symbol'], ['symbol'])

    op.create_table('stock',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stock_pkey'),
    sa.UniqueConstraint('symbol', name='stock_symbol_key')
    )
    # ### end Alembic commands ###
