"""empty message

Revision ID: f3c89f6d0df8
Revises: e7551410c9b6
Create Date: 2023-03-17 06:01:47.616706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c89f6d0df8'
down_revision = 'e7551410c9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('stock_symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('order_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.alter_column('stock_symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('stock_symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('stock_symbol',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.alter_column('stock_symbol',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('order_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('stock_symbol',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
